language: python
python: 3.5
branches:
  only:
  - build
before_install:
- openssl aes-256-cbc -K $encrypted_7b16cb35cfc7_key -iv $encrypted_7b16cb35cfc7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "fate0"
- git config --global user.email "fate0@fatezero.org"
- pip install git+https://github.com/fate0/getproxy.git@master
- git clone -b master --depth=2 git@github.com:fate0/proxylist.git deploy
install:
- getproxy --in-proxy=deploy/proxy.list --out-proxy=deploy/proxy.list.out
- mv deploy/proxy.list.out deploy/proxy.list
before_script:
- cd deploy
script:
- git add proxy.list
- git commit -m "`date`"
- git push -u origin master
